app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from contactfaces import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('contactfaces.urls')),
    url(r'', include('place.urls')),
    url(r'', include('shops.urls')),
    url(r'storages/', include('storages.urls')),
    url(r'^$', views.main),

]

contactfaces/urls.py
from django.conf.urls import url

from contactfaces.views import ContactFacesView, ContactDetailView

urlpatterns = [
    url(r'^contacts/$', ContactFacesView.as_view(), name='contacts'),
    url(r'^contacts-detail/(?P<pk>\d+)/$', ContactDetailView.as_view(), name='contacts_detail'),
]

contactfaces/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class ContactFaces(AbstractUser):
    MALE = 0
    FEMALE = 1
    SEX_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    sex = models.SmallIntegerField(choices=SEX_CHOICES, default=MALE)
    date_of_birth = models.DateField(null=True)
    team = models.IntegerField(choices=SEX_CHOICES, default=MALE)

    def __str__(self):
        return self.email

contactfaces/forms.py
# from django import forms
#
# from contactfaces.models import ContactFaces
#
# class ConactAddForm(forms.ModelForm):
#
#     class Meta:
#         model = ContactFaces
#         fields = ('')

contactfaces/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


# Create your views here.
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from contactfaces.models import ContactFaces


class ContactFacesView(ListView):

    model = ContactFaces
    context_object_name = 'contacts'
    template_name = 'contact_faces.html'


class ContactDetailView(DetailView):

    model = ContactFaces
    context_object_name = 'contact'
    template_name = 'contact_detail.html'


def main(request):

    return render(request, 'main.html', {})

contactfaces/templates/contact_detail.html
{% extends 'base.html'%}
{% block content %}
<br>
<div class="container">
    <h2 style="text-align:center;">{{ contact.username }}</h2>
    <ul class="list-group">
        <li class="list-group-item"><b>Email:</b> {{ contact.email }} </li>
        <li class="list-group-item"><b>Стать:</b> {{ contact.get_team_display }} </li>
        <li class="list-group-item"><b>День народження:</b> {{ contact.date_of_birth }} </li>
    </ul><br><br>
</div>
{% endblock %}

contactfaces/templates/contact_faces.html
{% extends 'base.html' %}

{% block content %}
<br><br>
<div class="container">
    {% for contact in contacts %}
         <nav aria-label="breadcrumb">
             <ol class="breadcrumb" style="background-color:#8acc51">
                 <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'contacts_detail' contact.pk  %}" style="color:black;">{{ contact.username }}</a></li>
            </ol>
         </nav>

    {% endfor %}
</div>


{% endblock %}